[package]
name = "LiftMetrics"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["datepicker"] }
rusqlite = "0.35.0"
